project:
  type: website
  output-dir: docs

website:
  title: "World Happiness with tidyverse"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: analysis/happiness-analysis.qmd
        text: Happiness analysis

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-summary: "Show code"